all:
  hosts:
    monitoring-vm-0:
      ansible_host: x.x.x.x
      ansible_user: rut
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
