{{- if .Values.postgresExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-exporter-service
spec:
  selector:
    app: postgres-exporter
  ports:
  - port: 9187
    targetPort: 9187
{{- end }}
